//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  post: Post;
  postConnection: PostConnection;
  note: Note;
  noteConnection: NoteConnection;
  blogroll: Blogroll;
  blogrollConnection: BlogrollConnection;
  book: Book;
  bookConnection: BookConnection;
  movie: Movie;
  movieConnection: MovieConnection;
  newsletter: Newsletter;
  newsletterConnection: NewsletterConnection;
  speaking: Speaking;
  speakingConnection: SpeakingConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPostArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPostConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PostFilter>;
};


export type QueryNoteArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNoteConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<NoteFilter>;
};


export type QueryBlogrollArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryBlogrollConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BlogrollFilter>;
};


export type QueryBookArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryBookConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BookFilter>;
};


export type QueryMovieArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryMovieConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<MovieFilter>;
};


export type QueryNewsletterArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNewsletterConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<NewsletterFilter>;
};


export type QuerySpeakingArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySpeakingConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SpeakingFilter>;
};

export type DocumentFilter = {
  post?: InputMaybe<PostFilter>;
  note?: InputMaybe<NoteFilter>;
  blogroll?: InputMaybe<BlogrollFilter>;
  book?: InputMaybe<BookFilter>;
  movie?: InputMaybe<MovieFilter>;
  newsletter?: InputMaybe<NewsletterFilter>;
  speaking?: InputMaybe<SpeakingFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Post | Note | Blogroll | Book | Movie | Newsletter | Speaking | Folder;

export type PostSeo = {
  __typename?: 'PostSeo';
  meta_title?: Maybe<Scalars['String']['output']>;
  meta_description?: Maybe<Scalars['String']['output']>;
  keywords?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type Post = Node & Document & {
  __typename?: 'Post';
  title: Scalars['String']['output'];
  publishDate: Scalars['String']['output'];
  author: Scalars['String']['output'];
  description: Scalars['String']['output'];
  featured_image?: Maybe<Scalars['String']['output']>;
  body: Scalars['JSON']['output'];
  categories?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  draft?: Maybe<Scalars['Boolean']['output']>;
  seo?: Maybe<PostSeo>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type PostSeoFilter = {
  meta_title?: InputMaybe<StringFilter>;
  meta_description?: InputMaybe<StringFilter>;
  keywords?: InputMaybe<StringFilter>;
};

export type PostFilter = {
  title?: InputMaybe<StringFilter>;
  publishDate?: InputMaybe<DatetimeFilter>;
  author?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  featured_image?: InputMaybe<ImageFilter>;
  body?: InputMaybe<RichTextFilter>;
  categories?: InputMaybe<StringFilter>;
  tags?: InputMaybe<StringFilter>;
  draft?: InputMaybe<BooleanFilter>;
  seo?: InputMaybe<PostSeoFilter>;
};

export type PostConnectionEdges = {
  __typename?: 'PostConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Post>;
};

export type PostConnection = Connection & {
  __typename?: 'PostConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PostConnectionEdges>>>;
};

export type Note = Node & Document & {
  __typename?: 'Note';
  pubDate: Scalars['String']['output'];
  featured_image?: Maybe<Scalars['String']['output']>;
  body: Scalars['JSON']['output'];
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type NoteFilter = {
  pubDate?: InputMaybe<DatetimeFilter>;
  featured_image?: InputMaybe<ImageFilter>;
  body?: InputMaybe<RichTextFilter>;
  tags?: InputMaybe<StringFilter>;
};

export type NoteConnectionEdges = {
  __typename?: 'NoteConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Note>;
};

export type NoteConnection = Connection & {
  __typename?: 'NoteConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<NoteConnectionEdges>>>;
};

export type Blogroll = Node & Document & {
  __typename?: 'Blogroll';
  title: Scalars['String']['output'];
  url: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  category: Scalars['String']['output'];
  rss_feed?: Maybe<Scalars['String']['output']>;
  date_added?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type BlogrollFilter = {
  title?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
  rss_feed?: InputMaybe<StringFilter>;
  date_added?: InputMaybe<DatetimeFilter>;
};

export type BlogrollConnectionEdges = {
  __typename?: 'BlogrollConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Blogroll>;
};

export type BlogrollConnection = Connection & {
  __typename?: 'BlogrollConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<BlogrollConnectionEdges>>>;
};

export type Book = Node & Document & {
  __typename?: 'Book';
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  author: Scalars['String']['output'];
  publishDate: Scalars['String']['output'];
  body?: Maybe<Scalars['JSON']['output']>;
  category: Array<Scalars['String']['output']>;
  cover?: Maybe<Scalars['String']['output']>;
  rating?: Maybe<Scalars['String']['output']>;
  status: Array<Scalars['String']['output']>;
  reading_date?: Maybe<Scalars['String']['output']>;
  pages?: Maybe<Scalars['Float']['output']>;
  recommended_for?: Maybe<Scalars['String']['output']>;
  purchase_link?: Maybe<Scalars['String']['output']>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type BookFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  author?: InputMaybe<StringFilter>;
  publishDate?: InputMaybe<DatetimeFilter>;
  body?: InputMaybe<RichTextFilter>;
  category?: InputMaybe<StringFilter>;
  cover?: InputMaybe<ImageFilter>;
  rating?: InputMaybe<StringFilter>;
  status?: InputMaybe<StringFilter>;
  reading_date?: InputMaybe<DatetimeFilter>;
  pages?: InputMaybe<NumberFilter>;
  recommended_for?: InputMaybe<StringFilter>;
  purchase_link?: InputMaybe<StringFilter>;
  tags?: InputMaybe<StringFilter>;
};

export type BookConnectionEdges = {
  __typename?: 'BookConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Book>;
};

export type BookConnection = Connection & {
  __typename?: 'BookConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<BookConnectionEdges>>>;
};

export type Movie = Node & Document & {
  __typename?: 'Movie';
  title: Scalars['String']['output'];
  body?: Maybe<Scalars['JSON']['output']>;
  genres: Array<Scalars['String']['output']>;
  poster?: Maybe<Scalars['String']['output']>;
  rating?: Maybe<Scalars['String']['output']>;
  status: Scalars['String']['output'];
  watched_date?: Maybe<Scalars['String']['output']>;
  favorite?: Maybe<Scalars['Boolean']['output']>;
  streaming?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  notes?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type MovieFilter = {
  title?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
  genres?: InputMaybe<StringFilter>;
  poster?: InputMaybe<ImageFilter>;
  rating?: InputMaybe<StringFilter>;
  status?: InputMaybe<StringFilter>;
  watched_date?: InputMaybe<DatetimeFilter>;
  favorite?: InputMaybe<BooleanFilter>;
  streaming?: InputMaybe<StringFilter>;
  tags?: InputMaybe<StringFilter>;
  notes?: InputMaybe<StringFilter>;
};

export type MovieConnectionEdges = {
  __typename?: 'MovieConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Movie>;
};

export type MovieConnection = Connection & {
  __typename?: 'MovieConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<MovieConnectionEdges>>>;
};

export type Newsletter = Node & Document & {
  __typename?: 'Newsletter';
  title: Scalars['String']['output'];
  issue: Scalars['String']['output'];
  coverImage?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type NewsletterFilter = {
  title?: InputMaybe<StringFilter>;
  issue?: InputMaybe<StringFilter>;
  coverImage?: InputMaybe<ImageFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type NewsletterConnectionEdges = {
  __typename?: 'NewsletterConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Newsletter>;
};

export type NewsletterConnection = Connection & {
  __typename?: 'NewsletterConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<NewsletterConnectionEdges>>>;
};

export type Speaking = Node & Document & {
  __typename?: 'Speaking';
  title: Scalars['String']['output'];
  issue: Scalars['String']['output'];
  coverImage?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type SpeakingFilter = {
  title?: InputMaybe<StringFilter>;
  issue?: InputMaybe<StringFilter>;
  coverImage?: InputMaybe<ImageFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type SpeakingConnectionEdges = {
  __typename?: 'SpeakingConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Speaking>;
};

export type SpeakingConnection = Connection & {
  __typename?: 'SpeakingConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SpeakingConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updatePost: Post;
  createPost: Post;
  updateNote: Note;
  createNote: Note;
  updateBlogroll: Blogroll;
  createBlogroll: Blogroll;
  updateBook: Book;
  createBook: Book;
  updateMovie: Movie;
  createMovie: Movie;
  updateNewsletter: Newsletter;
  createNewsletter: Newsletter;
  updateSpeaking: Speaking;
  createSpeaking: Speaking;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdatePostArgs = {
  relativePath: Scalars['String']['input'];
  params: PostMutation;
};


export type MutationCreatePostArgs = {
  relativePath: Scalars['String']['input'];
  params: PostMutation;
};


export type MutationUpdateNoteArgs = {
  relativePath: Scalars['String']['input'];
  params: NoteMutation;
};


export type MutationCreateNoteArgs = {
  relativePath: Scalars['String']['input'];
  params: NoteMutation;
};


export type MutationUpdateBlogrollArgs = {
  relativePath: Scalars['String']['input'];
  params: BlogrollMutation;
};


export type MutationCreateBlogrollArgs = {
  relativePath: Scalars['String']['input'];
  params: BlogrollMutation;
};


export type MutationUpdateBookArgs = {
  relativePath: Scalars['String']['input'];
  params: BookMutation;
};


export type MutationCreateBookArgs = {
  relativePath: Scalars['String']['input'];
  params: BookMutation;
};


export type MutationUpdateMovieArgs = {
  relativePath: Scalars['String']['input'];
  params: MovieMutation;
};


export type MutationCreateMovieArgs = {
  relativePath: Scalars['String']['input'];
  params: MovieMutation;
};


export type MutationUpdateNewsletterArgs = {
  relativePath: Scalars['String']['input'];
  params: NewsletterMutation;
};


export type MutationCreateNewsletterArgs = {
  relativePath: Scalars['String']['input'];
  params: NewsletterMutation;
};


export type MutationUpdateSpeakingArgs = {
  relativePath: Scalars['String']['input'];
  params: SpeakingMutation;
};


export type MutationCreateSpeakingArgs = {
  relativePath: Scalars['String']['input'];
  params: SpeakingMutation;
};

export type DocumentUpdateMutation = {
  post?: InputMaybe<PostMutation>;
  note?: InputMaybe<NoteMutation>;
  blogroll?: InputMaybe<BlogrollMutation>;
  book?: InputMaybe<BookMutation>;
  movie?: InputMaybe<MovieMutation>;
  newsletter?: InputMaybe<NewsletterMutation>;
  speaking?: InputMaybe<SpeakingMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  post?: InputMaybe<PostMutation>;
  note?: InputMaybe<NoteMutation>;
  blogroll?: InputMaybe<BlogrollMutation>;
  book?: InputMaybe<BookMutation>;
  movie?: InputMaybe<MovieMutation>;
  newsletter?: InputMaybe<NewsletterMutation>;
  speaking?: InputMaybe<SpeakingMutation>;
};

export type PostSeoMutation = {
  meta_title?: InputMaybe<Scalars['String']['input']>;
  meta_description?: InputMaybe<Scalars['String']['input']>;
  keywords?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type PostMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  publishDate?: InputMaybe<Scalars['String']['input']>;
  author?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  featured_image?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
  categories?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  draft?: InputMaybe<Scalars['Boolean']['input']>;
  seo?: InputMaybe<PostSeoMutation>;
};

export type NoteMutation = {
  pubDate?: InputMaybe<Scalars['String']['input']>;
  featured_image?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type BlogrollMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  rss_feed?: InputMaybe<Scalars['String']['input']>;
  date_added?: InputMaybe<Scalars['String']['input']>;
};

export type BookMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  author?: InputMaybe<Scalars['String']['input']>;
  publishDate?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
  category?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  cover?: InputMaybe<Scalars['String']['input']>;
  rating?: InputMaybe<Scalars['String']['input']>;
  status?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  reading_date?: InputMaybe<Scalars['String']['input']>;
  pages?: InputMaybe<Scalars['Float']['input']>;
  recommended_for?: InputMaybe<Scalars['String']['input']>;
  purchase_link?: InputMaybe<Scalars['String']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type MovieMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
  genres?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  poster?: InputMaybe<Scalars['String']['input']>;
  rating?: InputMaybe<Scalars['String']['input']>;
  status?: InputMaybe<Scalars['String']['input']>;
  watched_date?: InputMaybe<Scalars['String']['input']>;
  favorite?: InputMaybe<Scalars['Boolean']['input']>;
  streaming?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  notes?: InputMaybe<Scalars['String']['input']>;
};

export type NewsletterMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  issue?: InputMaybe<Scalars['String']['input']>;
  coverImage?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type SpeakingMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  issue?: InputMaybe<Scalars['String']['input']>;
  coverImage?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type PostPartsFragment = { __typename: 'Post', title: string, publishDate: string, author: string, description: string, featured_image?: string | null, body: any, categories?: Array<string | null> | null, tags?: Array<string | null> | null, draft?: boolean | null, seo?: { __typename: 'PostSeo', meta_title?: string | null, meta_description?: string | null, keywords?: Array<string | null> | null } | null };

export type NotePartsFragment = { __typename: 'Note', pubDate: string, featured_image?: string | null, body: any, tags?: Array<string | null> | null };

export type BlogrollPartsFragment = { __typename: 'Blogroll', title: string, url: string, description?: string | null, category: string, rss_feed?: string | null, date_added?: string | null };

export type BookPartsFragment = { __typename: 'Book', title: string, description?: string | null, author: string, publishDate: string, body?: any | null, category: Array<string>, cover?: string | null, rating?: string | null, status: Array<string>, reading_date?: string | null, pages?: number | null, recommended_for?: string | null, purchase_link?: string | null, tags?: Array<string | null> | null };

export type MoviePartsFragment = { __typename: 'Movie', title: string, body?: any | null, genres: Array<string>, poster?: string | null, rating?: string | null, status: string, watched_date?: string | null, favorite?: boolean | null, streaming?: Array<string | null> | null, tags?: Array<string | null> | null, notes?: string | null };

export type NewsletterPartsFragment = { __typename: 'Newsletter', title: string, issue: string, coverImage?: string | null, body?: any | null };

export type SpeakingPartsFragment = { __typename: 'Speaking', title: string, issue: string, coverImage?: string | null, body?: any | null };

export type PostQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PostQuery = { __typename?: 'Query', post: { __typename: 'Post', id: string, title: string, publishDate: string, author: string, description: string, featured_image?: string | null, body: any, categories?: Array<string | null> | null, tags?: Array<string | null> | null, draft?: boolean | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, seo?: { __typename: 'PostSeo', meta_title?: string | null, meta_description?: string | null, keywords?: Array<string | null> | null } | null } };

export type PostConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PostFilter>;
}>;


export type PostConnectionQuery = { __typename?: 'Query', postConnection: { __typename?: 'PostConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PostConnectionEdges', cursor: string, node?: { __typename: 'Post', id: string, title: string, publishDate: string, author: string, description: string, featured_image?: string | null, body: any, categories?: Array<string | null> | null, tags?: Array<string | null> | null, draft?: boolean | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, seo?: { __typename: 'PostSeo', meta_title?: string | null, meta_description?: string | null, keywords?: Array<string | null> | null } | null } | null } | null> | null } };

export type NoteQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type NoteQuery = { __typename?: 'Query', note: { __typename: 'Note', id: string, pubDate: string, featured_image?: string | null, body: any, tags?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type NoteConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<NoteFilter>;
}>;


export type NoteConnectionQuery = { __typename?: 'Query', noteConnection: { __typename?: 'NoteConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'NoteConnectionEdges', cursor: string, node?: { __typename: 'Note', id: string, pubDate: string, featured_image?: string | null, body: any, tags?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type BlogrollQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type BlogrollQuery = { __typename?: 'Query', blogroll: { __typename: 'Blogroll', id: string, title: string, url: string, description?: string | null, category: string, rss_feed?: string | null, date_added?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type BlogrollConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BlogrollFilter>;
}>;


export type BlogrollConnectionQuery = { __typename?: 'Query', blogrollConnection: { __typename?: 'BlogrollConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'BlogrollConnectionEdges', cursor: string, node?: { __typename: 'Blogroll', id: string, title: string, url: string, description?: string | null, category: string, rss_feed?: string | null, date_added?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type BookQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type BookQuery = { __typename?: 'Query', book: { __typename: 'Book', id: string, title: string, description?: string | null, author: string, publishDate: string, body?: any | null, category: Array<string>, cover?: string | null, rating?: string | null, status: Array<string>, reading_date?: string | null, pages?: number | null, recommended_for?: string | null, purchase_link?: string | null, tags?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type BookConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BookFilter>;
}>;


export type BookConnectionQuery = { __typename?: 'Query', bookConnection: { __typename?: 'BookConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'BookConnectionEdges', cursor: string, node?: { __typename: 'Book', id: string, title: string, description?: string | null, author: string, publishDate: string, body?: any | null, category: Array<string>, cover?: string | null, rating?: string | null, status: Array<string>, reading_date?: string | null, pages?: number | null, recommended_for?: string | null, purchase_link?: string | null, tags?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type MovieQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type MovieQuery = { __typename?: 'Query', movie: { __typename: 'Movie', id: string, title: string, body?: any | null, genres: Array<string>, poster?: string | null, rating?: string | null, status: string, watched_date?: string | null, favorite?: boolean | null, streaming?: Array<string | null> | null, tags?: Array<string | null> | null, notes?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type MovieConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<MovieFilter>;
}>;


export type MovieConnectionQuery = { __typename?: 'Query', movieConnection: { __typename?: 'MovieConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'MovieConnectionEdges', cursor: string, node?: { __typename: 'Movie', id: string, title: string, body?: any | null, genres: Array<string>, poster?: string | null, rating?: string | null, status: string, watched_date?: string | null, favorite?: boolean | null, streaming?: Array<string | null> | null, tags?: Array<string | null> | null, notes?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type NewsletterQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type NewsletterQuery = { __typename?: 'Query', newsletter: { __typename: 'Newsletter', id: string, title: string, issue: string, coverImage?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type NewsletterConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<NewsletterFilter>;
}>;


export type NewsletterConnectionQuery = { __typename?: 'Query', newsletterConnection: { __typename?: 'NewsletterConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'NewsletterConnectionEdges', cursor: string, node?: { __typename: 'Newsletter', id: string, title: string, issue: string, coverImage?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type SpeakingQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SpeakingQuery = { __typename?: 'Query', speaking: { __typename: 'Speaking', id: string, title: string, issue: string, coverImage?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type SpeakingConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SpeakingFilter>;
}>;


export type SpeakingConnectionQuery = { __typename?: 'Query', speakingConnection: { __typename?: 'SpeakingConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SpeakingConnectionEdges', cursor: string, node?: { __typename: 'Speaking', id: string, title: string, issue: string, coverImage?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const PostPartsFragmentDoc = gql`
    fragment PostParts on Post {
  __typename
  title
  publishDate
  author
  description
  featured_image
  body
  categories
  tags
  draft
  seo {
    __typename
    meta_title
    meta_description
    keywords
  }
}
    `;
export const NotePartsFragmentDoc = gql`
    fragment NoteParts on Note {
  __typename
  pubDate
  featured_image
  body
  tags
}
    `;
export const BlogrollPartsFragmentDoc = gql`
    fragment BlogrollParts on Blogroll {
  __typename
  title
  url
  description
  category
  rss_feed
  date_added
}
    `;
export const BookPartsFragmentDoc = gql`
    fragment BookParts on Book {
  __typename
  title
  description
  author
  publishDate
  body
  category
  cover
  rating
  status
  reading_date
  pages
  recommended_for
  purchase_link
  tags
}
    `;
export const MoviePartsFragmentDoc = gql`
    fragment MovieParts on Movie {
  __typename
  title
  body
  genres
  poster
  rating
  status
  watched_date
  favorite
  streaming
  tags
  notes
}
    `;
export const NewsletterPartsFragmentDoc = gql`
    fragment NewsletterParts on Newsletter {
  __typename
  title
  issue
  coverImage
  body
}
    `;
export const SpeakingPartsFragmentDoc = gql`
    fragment SpeakingParts on Speaking {
  __typename
  title
  issue
  coverImage
  body
}
    `;
export const PostDocument = gql`
    query post($relativePath: String!) {
  post(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PostParts
  }
}
    ${PostPartsFragmentDoc}`;
export const PostConnectionDocument = gql`
    query postConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PostFilter) {
  postConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PostParts
      }
    }
  }
}
    ${PostPartsFragmentDoc}`;
export const NoteDocument = gql`
    query note($relativePath: String!) {
  note(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...NoteParts
  }
}
    ${NotePartsFragmentDoc}`;
export const NoteConnectionDocument = gql`
    query noteConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: NoteFilter) {
  noteConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...NoteParts
      }
    }
  }
}
    ${NotePartsFragmentDoc}`;
export const BlogrollDocument = gql`
    query blogroll($relativePath: String!) {
  blogroll(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...BlogrollParts
  }
}
    ${BlogrollPartsFragmentDoc}`;
export const BlogrollConnectionDocument = gql`
    query blogrollConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: BlogrollFilter) {
  blogrollConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...BlogrollParts
      }
    }
  }
}
    ${BlogrollPartsFragmentDoc}`;
export const BookDocument = gql`
    query book($relativePath: String!) {
  book(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...BookParts
  }
}
    ${BookPartsFragmentDoc}`;
export const BookConnectionDocument = gql`
    query bookConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: BookFilter) {
  bookConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...BookParts
      }
    }
  }
}
    ${BookPartsFragmentDoc}`;
export const MovieDocument = gql`
    query movie($relativePath: String!) {
  movie(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...MovieParts
  }
}
    ${MoviePartsFragmentDoc}`;
export const MovieConnectionDocument = gql`
    query movieConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: MovieFilter) {
  movieConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...MovieParts
      }
    }
  }
}
    ${MoviePartsFragmentDoc}`;
export const NewsletterDocument = gql`
    query newsletter($relativePath: String!) {
  newsletter(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...NewsletterParts
  }
}
    ${NewsletterPartsFragmentDoc}`;
export const NewsletterConnectionDocument = gql`
    query newsletterConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: NewsletterFilter) {
  newsletterConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...NewsletterParts
      }
    }
  }
}
    ${NewsletterPartsFragmentDoc}`;
export const SpeakingDocument = gql`
    query speaking($relativePath: String!) {
  speaking(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SpeakingParts
  }
}
    ${SpeakingPartsFragmentDoc}`;
export const SpeakingConnectionDocument = gql`
    query speakingConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SpeakingFilter) {
  speakingConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SpeakingParts
      }
    }
  }
}
    ${SpeakingPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      post(variables: PostQueryVariables, options?: C): Promise<{data: PostQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PostQueryVariables, query: string}> {
        return requester<{data: PostQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PostQueryVariables, query: string}, PostQueryVariables>(PostDocument, variables, options);
      },
    postConnection(variables?: PostConnectionQueryVariables, options?: C): Promise<{data: PostConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PostConnectionQueryVariables, query: string}> {
        return requester<{data: PostConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PostConnectionQueryVariables, query: string}, PostConnectionQueryVariables>(PostConnectionDocument, variables, options);
      },
    note(variables: NoteQueryVariables, options?: C): Promise<{data: NoteQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NoteQueryVariables, query: string}> {
        return requester<{data: NoteQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NoteQueryVariables, query: string}, NoteQueryVariables>(NoteDocument, variables, options);
      },
    noteConnection(variables?: NoteConnectionQueryVariables, options?: C): Promise<{data: NoteConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NoteConnectionQueryVariables, query: string}> {
        return requester<{data: NoteConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NoteConnectionQueryVariables, query: string}, NoteConnectionQueryVariables>(NoteConnectionDocument, variables, options);
      },
    blogroll(variables: BlogrollQueryVariables, options?: C): Promise<{data: BlogrollQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogrollQueryVariables, query: string}> {
        return requester<{data: BlogrollQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogrollQueryVariables, query: string}, BlogrollQueryVariables>(BlogrollDocument, variables, options);
      },
    blogrollConnection(variables?: BlogrollConnectionQueryVariables, options?: C): Promise<{data: BlogrollConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogrollConnectionQueryVariables, query: string}> {
        return requester<{data: BlogrollConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogrollConnectionQueryVariables, query: string}, BlogrollConnectionQueryVariables>(BlogrollConnectionDocument, variables, options);
      },
    book(variables: BookQueryVariables, options?: C): Promise<{data: BookQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BookQueryVariables, query: string}> {
        return requester<{data: BookQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BookQueryVariables, query: string}, BookQueryVariables>(BookDocument, variables, options);
      },
    bookConnection(variables?: BookConnectionQueryVariables, options?: C): Promise<{data: BookConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BookConnectionQueryVariables, query: string}> {
        return requester<{data: BookConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BookConnectionQueryVariables, query: string}, BookConnectionQueryVariables>(BookConnectionDocument, variables, options);
      },
    movie(variables: MovieQueryVariables, options?: C): Promise<{data: MovieQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MovieQueryVariables, query: string}> {
        return requester<{data: MovieQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MovieQueryVariables, query: string}, MovieQueryVariables>(MovieDocument, variables, options);
      },
    movieConnection(variables?: MovieConnectionQueryVariables, options?: C): Promise<{data: MovieConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MovieConnectionQueryVariables, query: string}> {
        return requester<{data: MovieConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MovieConnectionQueryVariables, query: string}, MovieConnectionQueryVariables>(MovieConnectionDocument, variables, options);
      },
    newsletter(variables: NewsletterQueryVariables, options?: C): Promise<{data: NewsletterQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NewsletterQueryVariables, query: string}> {
        return requester<{data: NewsletterQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NewsletterQueryVariables, query: string}, NewsletterQueryVariables>(NewsletterDocument, variables, options);
      },
    newsletterConnection(variables?: NewsletterConnectionQueryVariables, options?: C): Promise<{data: NewsletterConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NewsletterConnectionQueryVariables, query: string}> {
        return requester<{data: NewsletterConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NewsletterConnectionQueryVariables, query: string}, NewsletterConnectionQueryVariables>(NewsletterConnectionDocument, variables, options);
      },
    speaking(variables: SpeakingQueryVariables, options?: C): Promise<{data: SpeakingQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SpeakingQueryVariables, query: string}> {
        return requester<{data: SpeakingQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SpeakingQueryVariables, query: string}, SpeakingQueryVariables>(SpeakingDocument, variables, options);
      },
    speakingConnection(variables?: SpeakingConnectionQueryVariables, options?: C): Promise<{data: SpeakingConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SpeakingConnectionQueryVariables, query: string}> {
        return requester<{data: SpeakingConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SpeakingConnectionQueryVariables, query: string}, SpeakingConnectionQueryVariables>(SpeakingConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  