//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  post: Post;
  postConnection: PostConnection;
  page: Page;
  pageConnection: PageConnection;
  service: Service;
  serviceConnection: ServiceConnection;
  note: Note;
  noteConnection: NoteConnection;
  book: Book;
  bookConnection: BookConnection;
  newsletter: Newsletter;
  newsletterConnection: NewsletterConnection;
  media: Media;
  mediaConnection: MediaConnection;
  bookmark: Bookmark;
  bookmarkConnection: BookmarkConnection;
  stream: Stream;
  streamConnection: StreamConnection;
  talk: Talk;
  talkConnection: TalkConnection;
  photos: Photos;
  photosConnection: PhotosConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPostArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPostConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PostFilter>;
};


export type QueryPageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PageFilter>;
};


export type QueryServiceArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryServiceConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ServiceFilter>;
};


export type QueryNoteArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNoteConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<NoteFilter>;
};


export type QueryBookArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryBookConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BookFilter>;
};


export type QueryNewsletterArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNewsletterConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<NewsletterFilter>;
};


export type QueryMediaArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryMediaConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<MediaFilter>;
};


export type QueryBookmarkArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryBookmarkConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BookmarkFilter>;
};


export type QueryStreamArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryStreamConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<StreamFilter>;
};


export type QueryTalkArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTalkConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TalkFilter>;
};


export type QueryPhotosArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPhotosConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PhotosFilter>;
};

export type DocumentFilter = {
  post?: InputMaybe<PostFilter>;
  page?: InputMaybe<PageFilter>;
  service?: InputMaybe<ServiceFilter>;
  note?: InputMaybe<NoteFilter>;
  book?: InputMaybe<BookFilter>;
  newsletter?: InputMaybe<NewsletterFilter>;
  media?: InputMaybe<MediaFilter>;
  bookmark?: InputMaybe<BookmarkFilter>;
  stream?: InputMaybe<StreamFilter>;
  talk?: InputMaybe<TalkFilter>;
  photos?: InputMaybe<PhotosFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Post | Page | Service | Note | Book | Newsletter | Media | Bookmark | Stream | Talk | Photos | Folder;

export type PostSeo = {
  __typename?: 'PostSeo';
  meta_title?: Maybe<Scalars['String']['output']>;
  meta_description?: Maybe<Scalars['String']['output']>;
  keywords?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type Post = Node & Document & {
  __typename?: 'Post';
  title: Scalars['String']['output'];
  date: Scalars['String']['output'];
  description: Scalars['String']['output'];
  featured_image?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  categories?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  draft?: Maybe<Scalars['Boolean']['output']>;
  seo?: Maybe<PostSeo>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type PostSeoFilter = {
  meta_title?: InputMaybe<StringFilter>;
  meta_description?: InputMaybe<StringFilter>;
  keywords?: InputMaybe<StringFilter>;
};

export type PostFilter = {
  title?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  description?: InputMaybe<StringFilter>;
  featured_image?: InputMaybe<ImageFilter>;
  body?: InputMaybe<RichTextFilter>;
  categories?: InputMaybe<StringFilter>;
  tags?: InputMaybe<StringFilter>;
  draft?: InputMaybe<BooleanFilter>;
  seo?: InputMaybe<PostSeoFilter>;
};

export type PostConnectionEdges = {
  __typename?: 'PostConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Post>;
};

export type PostConnection = Connection & {
  __typename?: 'PostConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PostConnectionEdges>>>;
};

export type Page = Node & Document & {
  __typename?: 'Page';
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  permalink?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PageFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  permalink?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type PageConnectionEdges = {
  __typename?: 'PageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Page>;
};

export type PageConnection = Connection & {
  __typename?: 'PageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PageConnectionEdges>>>;
};

export type ServiceServiceResults = {
  __typename?: 'ServiceServiceResults';
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type ServiceServiceProcesses = {
  __typename?: 'ServiceServiceProcesses';
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type ServiceServicePlans = {
  __typename?: 'ServiceServicePlans';
  name?: Maybe<Scalars['String']['output']>;
  highlight?: Maybe<Scalars['Boolean']['output']>;
  subtitle?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  includes?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  delivery?: Maybe<Scalars['String']['output']>;
};

export type ServiceServiceTestimonials = {
  __typename?: 'ServiceServiceTestimonials';
  cliente?: Maybe<Scalars['String']['output']>;
  quote?: Maybe<Scalars['String']['output']>;
  resultado?: Maybe<Scalars['String']['output']>;
};

export type ServiceServiceFaq = {
  __typename?: 'ServiceServiceFaq';
  question?: Maybe<Scalars['String']['output']>;
  answer?: Maybe<Scalars['String']['output']>;
};

export type ServiceServiceCta = {
  __typename?: 'ServiceServiceCta';
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  primary?: Maybe<Scalars['String']['output']>;
  secondary?: Maybe<Scalars['String']['output']>;
  link?: Maybe<Scalars['String']['output']>;
};

export type ServiceService = {
  __typename?: 'ServiceService';
  color?: Maybe<Scalars['String']['output']>;
  tagline?: Maybe<Scalars['String']['output']>;
  icon?: Maybe<Scalars['String']['output']>;
  problem?: Maybe<Scalars['String']['output']>;
  solution?: Maybe<Scalars['String']['output']>;
  differentials?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  included?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  results?: Maybe<Array<Maybe<ServiceServiceResults>>>;
  target?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  processes?: Maybe<Array<Maybe<ServiceServiceProcesses>>>;
  timeline?: Maybe<Scalars['String']['output']>;
  plans?: Maybe<Array<Maybe<ServiceServicePlans>>>;
  testimonials?: Maybe<ServiceServiceTestimonials>;
  faq?: Maybe<Array<Maybe<ServiceServiceFaq>>>;
  cta?: Maybe<ServiceServiceCta>;
};

export type Service = Node & Document & {
  __typename?: 'Service';
  title: Scalars['String']['output'];
  slug?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  permalink?: Maybe<Scalars['String']['output']>;
  url?: Maybe<Scalars['String']['output']>;
  service?: Maybe<ServiceService>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ServiceServiceResultsFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type ServiceServiceProcessesFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type ServiceServicePlansFilter = {
  name?: InputMaybe<StringFilter>;
  highlight?: InputMaybe<BooleanFilter>;
  subtitle?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  includes?: InputMaybe<StringFilter>;
  delivery?: InputMaybe<StringFilter>;
};

export type ServiceServiceTestimonialsFilter = {
  cliente?: InputMaybe<StringFilter>;
  quote?: InputMaybe<StringFilter>;
  resultado?: InputMaybe<StringFilter>;
};

export type ServiceServiceFaqFilter = {
  question?: InputMaybe<StringFilter>;
  answer?: InputMaybe<StringFilter>;
};

export type ServiceServiceCtaFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  primary?: InputMaybe<StringFilter>;
  secondary?: InputMaybe<StringFilter>;
  link?: InputMaybe<StringFilter>;
};

export type ServiceServiceFilter = {
  color?: InputMaybe<StringFilter>;
  tagline?: InputMaybe<StringFilter>;
  icon?: InputMaybe<StringFilter>;
  problem?: InputMaybe<StringFilter>;
  solution?: InputMaybe<StringFilter>;
  differentials?: InputMaybe<StringFilter>;
  included?: InputMaybe<StringFilter>;
  results?: InputMaybe<ServiceServiceResultsFilter>;
  target?: InputMaybe<StringFilter>;
  processes?: InputMaybe<ServiceServiceProcessesFilter>;
  timeline?: InputMaybe<StringFilter>;
  plans?: InputMaybe<ServiceServicePlansFilter>;
  testimonials?: InputMaybe<ServiceServiceTestimonialsFilter>;
  faq?: InputMaybe<ServiceServiceFaqFilter>;
  cta?: InputMaybe<ServiceServiceCtaFilter>;
};

export type ServiceFilter = {
  title?: InputMaybe<StringFilter>;
  slug?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  permalink?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
  service?: InputMaybe<ServiceServiceFilter>;
};

export type ServiceConnectionEdges = {
  __typename?: 'ServiceConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Service>;
};

export type ServiceConnection = Connection & {
  __typename?: 'ServiceConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ServiceConnectionEdges>>>;
};

export type Note = Node & Document & {
  __typename?: 'Note';
  title?: Maybe<Scalars['String']['output']>;
  pubDate: Scalars['String']['output'];
  published?: Maybe<Scalars['Boolean']['output']>;
  type?: Maybe<Scalars['String']['output']>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type NoteFilter = {
  title?: InputMaybe<StringFilter>;
  pubDate?: InputMaybe<DatetimeFilter>;
  published?: InputMaybe<BooleanFilter>;
  type?: InputMaybe<StringFilter>;
  tags?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type NoteConnectionEdges = {
  __typename?: 'NoteConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Note>;
};

export type NoteConnection = Connection & {
  __typename?: 'NoteConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<NoteConnectionEdges>>>;
};

export type Book = Node & Document & {
  __typename?: 'Book';
  title: Scalars['String']['output'];
  author?: Maybe<Scalars['String']['output']>;
  category?: Maybe<Scalars['String']['output']>;
  status?: Maybe<Scalars['String']['output']>;
  rating?: Maybe<Scalars['Float']['output']>;
  cover?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  thoughts?: Maybe<Scalars['String']['output']>;
  quotes?: Maybe<Scalars['String']['output']>;
  attendedYear?: Maybe<Scalars['Float']['output']>;
  recommendBy?: Maybe<Scalars['String']['output']>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  url?: Maybe<Scalars['String']['output']>;
  pubDate?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type BookFilter = {
  title?: InputMaybe<StringFilter>;
  author?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
  status?: InputMaybe<StringFilter>;
  rating?: InputMaybe<NumberFilter>;
  cover?: InputMaybe<ImageFilter>;
  description?: InputMaybe<StringFilter>;
  thoughts?: InputMaybe<StringFilter>;
  quotes?: InputMaybe<StringFilter>;
  attendedYear?: InputMaybe<NumberFilter>;
  recommendBy?: InputMaybe<StringFilter>;
  tags?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
  pubDate?: InputMaybe<DatetimeFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type BookConnectionEdges = {
  __typename?: 'BookConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Book>;
};

export type BookConnection = Connection & {
  __typename?: 'BookConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<BookConnectionEdges>>>;
};

export type Newsletter = Node & Document & {
  __typename?: 'Newsletter';
  title: Scalars['String']['output'];
  issue?: Maybe<Scalars['String']['output']>;
  pubDate?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type NewsletterFilter = {
  title?: InputMaybe<StringFilter>;
  issue?: InputMaybe<StringFilter>;
  pubDate?: InputMaybe<DatetimeFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type NewsletterConnectionEdges = {
  __typename?: 'NewsletterConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Newsletter>;
};

export type NewsletterConnection = Connection & {
  __typename?: 'NewsletterConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<NewsletterConnectionEdges>>>;
};

export type Media = Node & Document & {
  __typename?: 'Media';
  title: Scalars['String']['output'];
  director?: Maybe<Scalars['String']['output']>;
  category?: Maybe<Scalars['String']['output']>;
  status?: Maybe<Scalars['String']['output']>;
  rating?: Maybe<Scalars['Float']['output']>;
  poster?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  thoughts?: Maybe<Scalars['String']['output']>;
  watchedYear?: Maybe<Scalars['Float']['output']>;
  recommendBy?: Maybe<Scalars['String']['output']>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  url?: Maybe<Scalars['String']['output']>;
  watchedDate?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type MediaFilter = {
  title?: InputMaybe<StringFilter>;
  director?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
  status?: InputMaybe<StringFilter>;
  rating?: InputMaybe<NumberFilter>;
  poster?: InputMaybe<ImageFilter>;
  description?: InputMaybe<StringFilter>;
  thoughts?: InputMaybe<StringFilter>;
  watchedYear?: InputMaybe<NumberFilter>;
  recommendBy?: InputMaybe<StringFilter>;
  tags?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
  watchedDate?: InputMaybe<DatetimeFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type MediaConnectionEdges = {
  __typename?: 'MediaConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Media>;
};

export type MediaConnection = Connection & {
  __typename?: 'MediaConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<MediaConnectionEdges>>>;
};

export type Bookmark = Node & Document & {
  __typename?: 'Bookmark';
  title: Scalars['String']['output'];
  url?: Maybe<Scalars['String']['output']>;
  pubDate?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type BookmarkFilter = {
  title?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
  pubDate?: InputMaybe<DatetimeFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type BookmarkConnectionEdges = {
  __typename?: 'BookmarkConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Bookmark>;
};

export type BookmarkConnection = Connection & {
  __typename?: 'BookmarkConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<BookmarkConnectionEdges>>>;
};

export type Stream = Node & Document & {
  __typename?: 'Stream';
  title: Scalars['String']['output'];
  type?: Maybe<Scalars['String']['output']>;
  detail?: Maybe<Scalars['String']['output']>;
  pubDate?: Maybe<Scalars['String']['output']>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StreamFilter = {
  title?: InputMaybe<StringFilter>;
  type?: InputMaybe<StringFilter>;
  detail?: InputMaybe<StringFilter>;
  pubDate?: InputMaybe<DatetimeFilter>;
  tags?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type StreamConnectionEdges = {
  __typename?: 'StreamConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Stream>;
};

export type StreamConnection = Connection & {
  __typename?: 'StreamConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<StreamConnectionEdges>>>;
};

export type Talk = Node & Document & {
  __typename?: 'Talk';
  title: Scalars['String']['output'];
  date?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type TalkFilter = {
  title?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type TalkConnectionEdges = {
  __typename?: 'TalkConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Talk>;
};

export type TalkConnection = Connection & {
  __typename?: 'TalkConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<TalkConnectionEdges>>>;
};

export type Photos = Node & Document & {
  __typename?: 'Photos';
  title: Scalars['String']['output'];
  date?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PhotosFilter = {
  title?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  image?: InputMaybe<ImageFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type PhotosConnectionEdges = {
  __typename?: 'PhotosConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Photos>;
};

export type PhotosConnection = Connection & {
  __typename?: 'PhotosConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PhotosConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updatePost: Post;
  createPost: Post;
  updatePage: Page;
  createPage: Page;
  updateService: Service;
  createService: Service;
  updateNote: Note;
  createNote: Note;
  updateBook: Book;
  createBook: Book;
  updateNewsletter: Newsletter;
  createNewsletter: Newsletter;
  updateMedia: Media;
  createMedia: Media;
  updateBookmark: Bookmark;
  createBookmark: Bookmark;
  updateStream: Stream;
  createStream: Stream;
  updateTalk: Talk;
  createTalk: Talk;
  updatePhotos: Photos;
  createPhotos: Photos;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdatePostArgs = {
  relativePath: Scalars['String']['input'];
  params: PostMutation;
};


export type MutationCreatePostArgs = {
  relativePath: Scalars['String']['input'];
  params: PostMutation;
};


export type MutationUpdatePageArgs = {
  relativePath: Scalars['String']['input'];
  params: PageMutation;
};


export type MutationCreatePageArgs = {
  relativePath: Scalars['String']['input'];
  params: PageMutation;
};


export type MutationUpdateServiceArgs = {
  relativePath: Scalars['String']['input'];
  params: ServiceMutation;
};


export type MutationCreateServiceArgs = {
  relativePath: Scalars['String']['input'];
  params: ServiceMutation;
};


export type MutationUpdateNoteArgs = {
  relativePath: Scalars['String']['input'];
  params: NoteMutation;
};


export type MutationCreateNoteArgs = {
  relativePath: Scalars['String']['input'];
  params: NoteMutation;
};


export type MutationUpdateBookArgs = {
  relativePath: Scalars['String']['input'];
  params: BookMutation;
};


export type MutationCreateBookArgs = {
  relativePath: Scalars['String']['input'];
  params: BookMutation;
};


export type MutationUpdateNewsletterArgs = {
  relativePath: Scalars['String']['input'];
  params: NewsletterMutation;
};


export type MutationCreateNewsletterArgs = {
  relativePath: Scalars['String']['input'];
  params: NewsletterMutation;
};


export type MutationUpdateMediaArgs = {
  relativePath: Scalars['String']['input'];
  params: MediaMutation;
};


export type MutationCreateMediaArgs = {
  relativePath: Scalars['String']['input'];
  params: MediaMutation;
};


export type MutationUpdateBookmarkArgs = {
  relativePath: Scalars['String']['input'];
  params: BookmarkMutation;
};


export type MutationCreateBookmarkArgs = {
  relativePath: Scalars['String']['input'];
  params: BookmarkMutation;
};


export type MutationUpdateStreamArgs = {
  relativePath: Scalars['String']['input'];
  params: StreamMutation;
};


export type MutationCreateStreamArgs = {
  relativePath: Scalars['String']['input'];
  params: StreamMutation;
};


export type MutationUpdateTalkArgs = {
  relativePath: Scalars['String']['input'];
  params: TalkMutation;
};


export type MutationCreateTalkArgs = {
  relativePath: Scalars['String']['input'];
  params: TalkMutation;
};


export type MutationUpdatePhotosArgs = {
  relativePath: Scalars['String']['input'];
  params: PhotosMutation;
};


export type MutationCreatePhotosArgs = {
  relativePath: Scalars['String']['input'];
  params: PhotosMutation;
};

export type DocumentUpdateMutation = {
  post?: InputMaybe<PostMutation>;
  page?: InputMaybe<PageMutation>;
  service?: InputMaybe<ServiceMutation>;
  note?: InputMaybe<NoteMutation>;
  book?: InputMaybe<BookMutation>;
  newsletter?: InputMaybe<NewsletterMutation>;
  media?: InputMaybe<MediaMutation>;
  bookmark?: InputMaybe<BookmarkMutation>;
  stream?: InputMaybe<StreamMutation>;
  talk?: InputMaybe<TalkMutation>;
  photos?: InputMaybe<PhotosMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  post?: InputMaybe<PostMutation>;
  page?: InputMaybe<PageMutation>;
  service?: InputMaybe<ServiceMutation>;
  note?: InputMaybe<NoteMutation>;
  book?: InputMaybe<BookMutation>;
  newsletter?: InputMaybe<NewsletterMutation>;
  media?: InputMaybe<MediaMutation>;
  bookmark?: InputMaybe<BookmarkMutation>;
  stream?: InputMaybe<StreamMutation>;
  talk?: InputMaybe<TalkMutation>;
  photos?: InputMaybe<PhotosMutation>;
};

export type PostSeoMutation = {
  meta_title?: InputMaybe<Scalars['String']['input']>;
  meta_description?: InputMaybe<Scalars['String']['input']>;
  keywords?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type PostMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  featured_image?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
  categories?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  draft?: InputMaybe<Scalars['Boolean']['input']>;
  seo?: InputMaybe<PostSeoMutation>;
};

export type PageMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  permalink?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type ServiceServiceResultsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type ServiceServiceProcessesMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type ServiceServicePlansMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  highlight?: InputMaybe<Scalars['Boolean']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  includes?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  delivery?: InputMaybe<Scalars['String']['input']>;
};

export type ServiceServiceTestimonialsMutation = {
  cliente?: InputMaybe<Scalars['String']['input']>;
  quote?: InputMaybe<Scalars['String']['input']>;
  resultado?: InputMaybe<Scalars['String']['input']>;
};

export type ServiceServiceFaqMutation = {
  question?: InputMaybe<Scalars['String']['input']>;
  answer?: InputMaybe<Scalars['String']['input']>;
};

export type ServiceServiceCtaMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  primary?: InputMaybe<Scalars['String']['input']>;
  secondary?: InputMaybe<Scalars['String']['input']>;
  link?: InputMaybe<Scalars['String']['input']>;
};

export type ServiceServiceMutation = {
  color?: InputMaybe<Scalars['String']['input']>;
  tagline?: InputMaybe<Scalars['String']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
  problem?: InputMaybe<Scalars['String']['input']>;
  solution?: InputMaybe<Scalars['String']['input']>;
  differentials?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  included?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  results?: InputMaybe<Array<InputMaybe<ServiceServiceResultsMutation>>>;
  target?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  processes?: InputMaybe<Array<InputMaybe<ServiceServiceProcessesMutation>>>;
  timeline?: InputMaybe<Scalars['String']['input']>;
  plans?: InputMaybe<Array<InputMaybe<ServiceServicePlansMutation>>>;
  testimonials?: InputMaybe<ServiceServiceTestimonialsMutation>;
  faq?: InputMaybe<Array<InputMaybe<ServiceServiceFaqMutation>>>;
  cta?: InputMaybe<ServiceServiceCtaMutation>;
};

export type ServiceMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  permalink?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
  service?: InputMaybe<ServiceServiceMutation>;
};

export type NoteMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  pubDate?: InputMaybe<Scalars['String']['input']>;
  published?: InputMaybe<Scalars['Boolean']['input']>;
  type?: InputMaybe<Scalars['String']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type BookMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  author?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  status?: InputMaybe<Scalars['String']['input']>;
  rating?: InputMaybe<Scalars['Float']['input']>;
  cover?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  thoughts?: InputMaybe<Scalars['String']['input']>;
  quotes?: InputMaybe<Scalars['String']['input']>;
  attendedYear?: InputMaybe<Scalars['Float']['input']>;
  recommendBy?: InputMaybe<Scalars['String']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  url?: InputMaybe<Scalars['String']['input']>;
  pubDate?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type NewsletterMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  issue?: InputMaybe<Scalars['String']['input']>;
  pubDate?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type MediaMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  director?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  status?: InputMaybe<Scalars['String']['input']>;
  rating?: InputMaybe<Scalars['Float']['input']>;
  poster?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  thoughts?: InputMaybe<Scalars['String']['input']>;
  watchedYear?: InputMaybe<Scalars['Float']['input']>;
  recommendBy?: InputMaybe<Scalars['String']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  url?: InputMaybe<Scalars['String']['input']>;
  watchedDate?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type BookmarkMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
  pubDate?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type StreamMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  type?: InputMaybe<Scalars['String']['input']>;
  detail?: InputMaybe<Scalars['String']['input']>;
  pubDate?: InputMaybe<Scalars['String']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type TalkMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type PhotosMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type PostPartsFragment = { __typename: 'Post', title: string, date: string, description: string, featured_image?: string | null, body?: any | null, categories?: Array<string | null> | null, tags?: Array<string | null> | null, draft?: boolean | null, seo?: { __typename: 'PostSeo', meta_title?: string | null, meta_description?: string | null, keywords?: Array<string | null> | null } | null };

export type PagePartsFragment = { __typename: 'Page', title: string, description?: string | null, permalink?: string | null, body?: any | null };

export type ServicePartsFragment = { __typename: 'Service', title: string, slug?: string | null, description?: string | null, permalink?: string | null, url?: string | null, service?: { __typename: 'ServiceService', color?: string | null, tagline?: string | null, icon?: string | null, problem?: string | null, solution?: string | null, differentials?: Array<string | null> | null, included?: Array<string | null> | null, target?: Array<string | null> | null, timeline?: string | null, results?: Array<{ __typename: 'ServiceServiceResults', title?: string | null, description?: string | null } | null> | null, processes?: Array<{ __typename: 'ServiceServiceProcesses', title?: string | null, description?: string | null } | null> | null, plans?: Array<{ __typename: 'ServiceServicePlans', name?: string | null, highlight?: boolean | null, subtitle?: string | null, description?: string | null, includes?: Array<string | null> | null, delivery?: string | null } | null> | null, testimonials?: { __typename: 'ServiceServiceTestimonials', cliente?: string | null, quote?: string | null, resultado?: string | null } | null, faq?: Array<{ __typename: 'ServiceServiceFaq', question?: string | null, answer?: string | null } | null> | null, cta?: { __typename: 'ServiceServiceCta', title?: string | null, description?: string | null, primary?: string | null, secondary?: string | null, link?: string | null } | null } | null };

export type NotePartsFragment = { __typename: 'Note', title?: string | null, pubDate: string, published?: boolean | null, type?: string | null, tags?: Array<string | null> | null, body?: any | null };

export type BookPartsFragment = { __typename: 'Book', title: string, author?: string | null, category?: string | null, status?: string | null, rating?: number | null, cover?: string | null, description?: string | null, thoughts?: string | null, quotes?: string | null, attendedYear?: number | null, recommendBy?: string | null, tags?: Array<string | null> | null, url?: string | null, pubDate?: string | null, body?: any | null };

export type NewsletterPartsFragment = { __typename: 'Newsletter', title: string, issue?: string | null, pubDate?: string | null, body?: any | null };

export type MediaPartsFragment = { __typename: 'Media', title: string, director?: string | null, category?: string | null, status?: string | null, rating?: number | null, poster?: string | null, description?: string | null, thoughts?: string | null, watchedYear?: number | null, recommendBy?: string | null, tags?: Array<string | null> | null, url?: string | null, watchedDate?: string | null, body?: any | null };

export type BookmarkPartsFragment = { __typename: 'Bookmark', title: string, url?: string | null, pubDate?: string | null, body?: any | null };

export type StreamPartsFragment = { __typename: 'Stream', title: string, type?: string | null, detail?: string | null, pubDate?: string | null, tags?: Array<string | null> | null, body?: any | null };

export type TalkPartsFragment = { __typename: 'Talk', title: string, date?: string | null, body?: any | null };

export type PhotosPartsFragment = { __typename: 'Photos', title: string, date?: string | null, image?: string | null, body?: any | null };

export type PostQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PostQuery = { __typename?: 'Query', post: { __typename: 'Post', id: string, title: string, date: string, description: string, featured_image?: string | null, body?: any | null, categories?: Array<string | null> | null, tags?: Array<string | null> | null, draft?: boolean | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, seo?: { __typename: 'PostSeo', meta_title?: string | null, meta_description?: string | null, keywords?: Array<string | null> | null } | null } };

export type PostConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PostFilter>;
}>;


export type PostConnectionQuery = { __typename?: 'Query', postConnection: { __typename?: 'PostConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PostConnectionEdges', cursor: string, node?: { __typename: 'Post', id: string, title: string, date: string, description: string, featured_image?: string | null, body?: any | null, categories?: Array<string | null> | null, tags?: Array<string | null> | null, draft?: boolean | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, seo?: { __typename: 'PostSeo', meta_title?: string | null, meta_description?: string | null, keywords?: Array<string | null> | null } | null } | null } | null> | null } };

export type PageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PageQuery = { __typename?: 'Query', page: { __typename: 'Page', id: string, title: string, description?: string | null, permalink?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type PageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PageFilter>;
}>;


export type PageConnectionQuery = { __typename?: 'Query', pageConnection: { __typename?: 'PageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PageConnectionEdges', cursor: string, node?: { __typename: 'Page', id: string, title: string, description?: string | null, permalink?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type ServiceQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ServiceQuery = { __typename?: 'Query', service: { __typename: 'Service', id: string, title: string, slug?: string | null, description?: string | null, permalink?: string | null, url?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, service?: { __typename: 'ServiceService', color?: string | null, tagline?: string | null, icon?: string | null, problem?: string | null, solution?: string | null, differentials?: Array<string | null> | null, included?: Array<string | null> | null, target?: Array<string | null> | null, timeline?: string | null, results?: Array<{ __typename: 'ServiceServiceResults', title?: string | null, description?: string | null } | null> | null, processes?: Array<{ __typename: 'ServiceServiceProcesses', title?: string | null, description?: string | null } | null> | null, plans?: Array<{ __typename: 'ServiceServicePlans', name?: string | null, highlight?: boolean | null, subtitle?: string | null, description?: string | null, includes?: Array<string | null> | null, delivery?: string | null } | null> | null, testimonials?: { __typename: 'ServiceServiceTestimonials', cliente?: string | null, quote?: string | null, resultado?: string | null } | null, faq?: Array<{ __typename: 'ServiceServiceFaq', question?: string | null, answer?: string | null } | null> | null, cta?: { __typename: 'ServiceServiceCta', title?: string | null, description?: string | null, primary?: string | null, secondary?: string | null, link?: string | null } | null } | null } };

export type ServiceConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ServiceFilter>;
}>;


export type ServiceConnectionQuery = { __typename?: 'Query', serviceConnection: { __typename?: 'ServiceConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ServiceConnectionEdges', cursor: string, node?: { __typename: 'Service', id: string, title: string, slug?: string | null, description?: string | null, permalink?: string | null, url?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, service?: { __typename: 'ServiceService', color?: string | null, tagline?: string | null, icon?: string | null, problem?: string | null, solution?: string | null, differentials?: Array<string | null> | null, included?: Array<string | null> | null, target?: Array<string | null> | null, timeline?: string | null, results?: Array<{ __typename: 'ServiceServiceResults', title?: string | null, description?: string | null } | null> | null, processes?: Array<{ __typename: 'ServiceServiceProcesses', title?: string | null, description?: string | null } | null> | null, plans?: Array<{ __typename: 'ServiceServicePlans', name?: string | null, highlight?: boolean | null, subtitle?: string | null, description?: string | null, includes?: Array<string | null> | null, delivery?: string | null } | null> | null, testimonials?: { __typename: 'ServiceServiceTestimonials', cliente?: string | null, quote?: string | null, resultado?: string | null } | null, faq?: Array<{ __typename: 'ServiceServiceFaq', question?: string | null, answer?: string | null } | null> | null, cta?: { __typename: 'ServiceServiceCta', title?: string | null, description?: string | null, primary?: string | null, secondary?: string | null, link?: string | null } | null } | null } | null } | null> | null } };

export type NoteQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type NoteQuery = { __typename?: 'Query', note: { __typename: 'Note', id: string, title?: string | null, pubDate: string, published?: boolean | null, type?: string | null, tags?: Array<string | null> | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type NoteConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<NoteFilter>;
}>;


export type NoteConnectionQuery = { __typename?: 'Query', noteConnection: { __typename?: 'NoteConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'NoteConnectionEdges', cursor: string, node?: { __typename: 'Note', id: string, title?: string | null, pubDate: string, published?: boolean | null, type?: string | null, tags?: Array<string | null> | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type BookQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type BookQuery = { __typename?: 'Query', book: { __typename: 'Book', id: string, title: string, author?: string | null, category?: string | null, status?: string | null, rating?: number | null, cover?: string | null, description?: string | null, thoughts?: string | null, quotes?: string | null, attendedYear?: number | null, recommendBy?: string | null, tags?: Array<string | null> | null, url?: string | null, pubDate?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type BookConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BookFilter>;
}>;


export type BookConnectionQuery = { __typename?: 'Query', bookConnection: { __typename?: 'BookConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'BookConnectionEdges', cursor: string, node?: { __typename: 'Book', id: string, title: string, author?: string | null, category?: string | null, status?: string | null, rating?: number | null, cover?: string | null, description?: string | null, thoughts?: string | null, quotes?: string | null, attendedYear?: number | null, recommendBy?: string | null, tags?: Array<string | null> | null, url?: string | null, pubDate?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type NewsletterQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type NewsletterQuery = { __typename?: 'Query', newsletter: { __typename: 'Newsletter', id: string, title: string, issue?: string | null, pubDate?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type NewsletterConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<NewsletterFilter>;
}>;


export type NewsletterConnectionQuery = { __typename?: 'Query', newsletterConnection: { __typename?: 'NewsletterConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'NewsletterConnectionEdges', cursor: string, node?: { __typename: 'Newsletter', id: string, title: string, issue?: string | null, pubDate?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type MediaQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type MediaQuery = { __typename?: 'Query', media: { __typename: 'Media', id: string, title: string, director?: string | null, category?: string | null, status?: string | null, rating?: number | null, poster?: string | null, description?: string | null, thoughts?: string | null, watchedYear?: number | null, recommendBy?: string | null, tags?: Array<string | null> | null, url?: string | null, watchedDate?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type MediaConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<MediaFilter>;
}>;


export type MediaConnectionQuery = { __typename?: 'Query', mediaConnection: { __typename?: 'MediaConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'MediaConnectionEdges', cursor: string, node?: { __typename: 'Media', id: string, title: string, director?: string | null, category?: string | null, status?: string | null, rating?: number | null, poster?: string | null, description?: string | null, thoughts?: string | null, watchedYear?: number | null, recommendBy?: string | null, tags?: Array<string | null> | null, url?: string | null, watchedDate?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type BookmarkQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type BookmarkQuery = { __typename?: 'Query', bookmark: { __typename: 'Bookmark', id: string, title: string, url?: string | null, pubDate?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type BookmarkConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BookmarkFilter>;
}>;


export type BookmarkConnectionQuery = { __typename?: 'Query', bookmarkConnection: { __typename?: 'BookmarkConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'BookmarkConnectionEdges', cursor: string, node?: { __typename: 'Bookmark', id: string, title: string, url?: string | null, pubDate?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type StreamQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type StreamQuery = { __typename?: 'Query', stream: { __typename: 'Stream', id: string, title: string, type?: string | null, detail?: string | null, pubDate?: string | null, tags?: Array<string | null> | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type StreamConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<StreamFilter>;
}>;


export type StreamConnectionQuery = { __typename?: 'Query', streamConnection: { __typename?: 'StreamConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'StreamConnectionEdges', cursor: string, node?: { __typename: 'Stream', id: string, title: string, type?: string | null, detail?: string | null, pubDate?: string | null, tags?: Array<string | null> | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type TalkQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type TalkQuery = { __typename?: 'Query', talk: { __typename: 'Talk', id: string, title: string, date?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type TalkConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TalkFilter>;
}>;


export type TalkConnectionQuery = { __typename?: 'Query', talkConnection: { __typename?: 'TalkConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'TalkConnectionEdges', cursor: string, node?: { __typename: 'Talk', id: string, title: string, date?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type PhotosQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PhotosQuery = { __typename?: 'Query', photos: { __typename: 'Photos', id: string, title: string, date?: string | null, image?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type PhotosConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PhotosFilter>;
}>;


export type PhotosConnectionQuery = { __typename?: 'Query', photosConnection: { __typename?: 'PhotosConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PhotosConnectionEdges', cursor: string, node?: { __typename: 'Photos', id: string, title: string, date?: string | null, image?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const PostPartsFragmentDoc = gql`
    fragment PostParts on Post {
  __typename
  title
  date
  description
  featured_image
  body
  categories
  tags
  draft
  seo {
    __typename
    meta_title
    meta_description
    keywords
  }
}
    `;
export const PagePartsFragmentDoc = gql`
    fragment PageParts on Page {
  __typename
  title
  description
  permalink
  body
}
    `;
export const ServicePartsFragmentDoc = gql`
    fragment ServiceParts on Service {
  __typename
  title
  slug
  description
  permalink
  url
  service {
    __typename
    color
    tagline
    icon
    problem
    solution
    differentials
    included
    results {
      __typename
      title
      description
    }
    target
    processes {
      __typename
      title
      description
    }
    timeline
    plans {
      __typename
      name
      highlight
      subtitle
      description
      includes
      delivery
    }
    testimonials {
      __typename
      cliente
      quote
      resultado
    }
    faq {
      __typename
      question
      answer
    }
    cta {
      __typename
      title
      description
      primary
      secondary
      link
    }
  }
}
    `;
export const NotePartsFragmentDoc = gql`
    fragment NoteParts on Note {
  __typename
  title
  pubDate
  published
  type
  tags
  body
}
    `;
export const BookPartsFragmentDoc = gql`
    fragment BookParts on Book {
  __typename
  title
  author
  category
  status
  rating
  cover
  description
  thoughts
  quotes
  attendedYear
  recommendBy
  tags
  url
  pubDate
  body
}
    `;
export const NewsletterPartsFragmentDoc = gql`
    fragment NewsletterParts on Newsletter {
  __typename
  title
  issue
  pubDate
  body
}
    `;
export const MediaPartsFragmentDoc = gql`
    fragment MediaParts on Media {
  __typename
  title
  director
  category
  status
  rating
  poster
  description
  thoughts
  watchedYear
  recommendBy
  tags
  url
  watchedDate
  body
}
    `;
export const BookmarkPartsFragmentDoc = gql`
    fragment BookmarkParts on Bookmark {
  __typename
  title
  url
  pubDate
  body
}
    `;
export const StreamPartsFragmentDoc = gql`
    fragment StreamParts on Stream {
  __typename
  title
  type
  detail
  pubDate
  tags
  body
}
    `;
export const TalkPartsFragmentDoc = gql`
    fragment TalkParts on Talk {
  __typename
  title
  date
  body
}
    `;
export const PhotosPartsFragmentDoc = gql`
    fragment PhotosParts on Photos {
  __typename
  title
  date
  image
  body
}
    `;
export const PostDocument = gql`
    query post($relativePath: String!) {
  post(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PostParts
  }
}
    ${PostPartsFragmentDoc}`;
export const PostConnectionDocument = gql`
    query postConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PostFilter) {
  postConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PostParts
      }
    }
  }
}
    ${PostPartsFragmentDoc}`;
export const PageDocument = gql`
    query page($relativePath: String!) {
  page(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PageParts
  }
}
    ${PagePartsFragmentDoc}`;
export const PageConnectionDocument = gql`
    query pageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PageFilter) {
  pageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PageParts
      }
    }
  }
}
    ${PagePartsFragmentDoc}`;
export const ServiceDocument = gql`
    query service($relativePath: String!) {
  service(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ServiceParts
  }
}
    ${ServicePartsFragmentDoc}`;
export const ServiceConnectionDocument = gql`
    query serviceConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ServiceFilter) {
  serviceConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ServiceParts
      }
    }
  }
}
    ${ServicePartsFragmentDoc}`;
export const NoteDocument = gql`
    query note($relativePath: String!) {
  note(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...NoteParts
  }
}
    ${NotePartsFragmentDoc}`;
export const NoteConnectionDocument = gql`
    query noteConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: NoteFilter) {
  noteConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...NoteParts
      }
    }
  }
}
    ${NotePartsFragmentDoc}`;
export const BookDocument = gql`
    query book($relativePath: String!) {
  book(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...BookParts
  }
}
    ${BookPartsFragmentDoc}`;
export const BookConnectionDocument = gql`
    query bookConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: BookFilter) {
  bookConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...BookParts
      }
    }
  }
}
    ${BookPartsFragmentDoc}`;
export const NewsletterDocument = gql`
    query newsletter($relativePath: String!) {
  newsletter(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...NewsletterParts
  }
}
    ${NewsletterPartsFragmentDoc}`;
export const NewsletterConnectionDocument = gql`
    query newsletterConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: NewsletterFilter) {
  newsletterConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...NewsletterParts
      }
    }
  }
}
    ${NewsletterPartsFragmentDoc}`;
export const MediaDocument = gql`
    query media($relativePath: String!) {
  media(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...MediaParts
  }
}
    ${MediaPartsFragmentDoc}`;
export const MediaConnectionDocument = gql`
    query mediaConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: MediaFilter) {
  mediaConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...MediaParts
      }
    }
  }
}
    ${MediaPartsFragmentDoc}`;
export const BookmarkDocument = gql`
    query bookmark($relativePath: String!) {
  bookmark(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...BookmarkParts
  }
}
    ${BookmarkPartsFragmentDoc}`;
export const BookmarkConnectionDocument = gql`
    query bookmarkConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: BookmarkFilter) {
  bookmarkConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...BookmarkParts
      }
    }
  }
}
    ${BookmarkPartsFragmentDoc}`;
export const StreamDocument = gql`
    query stream($relativePath: String!) {
  stream(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...StreamParts
  }
}
    ${StreamPartsFragmentDoc}`;
export const StreamConnectionDocument = gql`
    query streamConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: StreamFilter) {
  streamConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...StreamParts
      }
    }
  }
}
    ${StreamPartsFragmentDoc}`;
export const TalkDocument = gql`
    query talk($relativePath: String!) {
  talk(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...TalkParts
  }
}
    ${TalkPartsFragmentDoc}`;
export const TalkConnectionDocument = gql`
    query talkConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: TalkFilter) {
  talkConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...TalkParts
      }
    }
  }
}
    ${TalkPartsFragmentDoc}`;
export const PhotosDocument = gql`
    query photos($relativePath: String!) {
  photos(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PhotosParts
  }
}
    ${PhotosPartsFragmentDoc}`;
export const PhotosConnectionDocument = gql`
    query photosConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PhotosFilter) {
  photosConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PhotosParts
      }
    }
  }
}
    ${PhotosPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      post(variables: PostQueryVariables, options?: C): Promise<{data: PostQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PostQueryVariables, query: string}> {
        return requester<{data: PostQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PostQueryVariables, query: string}, PostQueryVariables>(PostDocument, variables, options);
      },
    postConnection(variables?: PostConnectionQueryVariables, options?: C): Promise<{data: PostConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PostConnectionQueryVariables, query: string}> {
        return requester<{data: PostConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PostConnectionQueryVariables, query: string}, PostConnectionQueryVariables>(PostConnectionDocument, variables, options);
      },
    page(variables: PageQueryVariables, options?: C): Promise<{data: PageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageQueryVariables, query: string}> {
        return requester<{data: PageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageQueryVariables, query: string}, PageQueryVariables>(PageDocument, variables, options);
      },
    pageConnection(variables?: PageConnectionQueryVariables, options?: C): Promise<{data: PageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageConnectionQueryVariables, query: string}> {
        return requester<{data: PageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageConnectionQueryVariables, query: string}, PageConnectionQueryVariables>(PageConnectionDocument, variables, options);
      },
    service(variables: ServiceQueryVariables, options?: C): Promise<{data: ServiceQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServiceQueryVariables, query: string}> {
        return requester<{data: ServiceQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServiceQueryVariables, query: string}, ServiceQueryVariables>(ServiceDocument, variables, options);
      },
    serviceConnection(variables?: ServiceConnectionQueryVariables, options?: C): Promise<{data: ServiceConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServiceConnectionQueryVariables, query: string}> {
        return requester<{data: ServiceConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServiceConnectionQueryVariables, query: string}, ServiceConnectionQueryVariables>(ServiceConnectionDocument, variables, options);
      },
    note(variables: NoteQueryVariables, options?: C): Promise<{data: NoteQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NoteQueryVariables, query: string}> {
        return requester<{data: NoteQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NoteQueryVariables, query: string}, NoteQueryVariables>(NoteDocument, variables, options);
      },
    noteConnection(variables?: NoteConnectionQueryVariables, options?: C): Promise<{data: NoteConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NoteConnectionQueryVariables, query: string}> {
        return requester<{data: NoteConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NoteConnectionQueryVariables, query: string}, NoteConnectionQueryVariables>(NoteConnectionDocument, variables, options);
      },
    book(variables: BookQueryVariables, options?: C): Promise<{data: BookQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BookQueryVariables, query: string}> {
        return requester<{data: BookQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BookQueryVariables, query: string}, BookQueryVariables>(BookDocument, variables, options);
      },
    bookConnection(variables?: BookConnectionQueryVariables, options?: C): Promise<{data: BookConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BookConnectionQueryVariables, query: string}> {
        return requester<{data: BookConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BookConnectionQueryVariables, query: string}, BookConnectionQueryVariables>(BookConnectionDocument, variables, options);
      },
    newsletter(variables: NewsletterQueryVariables, options?: C): Promise<{data: NewsletterQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NewsletterQueryVariables, query: string}> {
        return requester<{data: NewsletterQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NewsletterQueryVariables, query: string}, NewsletterQueryVariables>(NewsletterDocument, variables, options);
      },
    newsletterConnection(variables?: NewsletterConnectionQueryVariables, options?: C): Promise<{data: NewsletterConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NewsletterConnectionQueryVariables, query: string}> {
        return requester<{data: NewsletterConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NewsletterConnectionQueryVariables, query: string}, NewsletterConnectionQueryVariables>(NewsletterConnectionDocument, variables, options);
      },
    media(variables: MediaQueryVariables, options?: C): Promise<{data: MediaQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MediaQueryVariables, query: string}> {
        return requester<{data: MediaQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MediaQueryVariables, query: string}, MediaQueryVariables>(MediaDocument, variables, options);
      },
    mediaConnection(variables?: MediaConnectionQueryVariables, options?: C): Promise<{data: MediaConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MediaConnectionQueryVariables, query: string}> {
        return requester<{data: MediaConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MediaConnectionQueryVariables, query: string}, MediaConnectionQueryVariables>(MediaConnectionDocument, variables, options);
      },
    bookmark(variables: BookmarkQueryVariables, options?: C): Promise<{data: BookmarkQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BookmarkQueryVariables, query: string}> {
        return requester<{data: BookmarkQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BookmarkQueryVariables, query: string}, BookmarkQueryVariables>(BookmarkDocument, variables, options);
      },
    bookmarkConnection(variables?: BookmarkConnectionQueryVariables, options?: C): Promise<{data: BookmarkConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BookmarkConnectionQueryVariables, query: string}> {
        return requester<{data: BookmarkConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BookmarkConnectionQueryVariables, query: string}, BookmarkConnectionQueryVariables>(BookmarkConnectionDocument, variables, options);
      },
    stream(variables: StreamQueryVariables, options?: C): Promise<{data: StreamQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: StreamQueryVariables, query: string}> {
        return requester<{data: StreamQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: StreamQueryVariables, query: string}, StreamQueryVariables>(StreamDocument, variables, options);
      },
    streamConnection(variables?: StreamConnectionQueryVariables, options?: C): Promise<{data: StreamConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: StreamConnectionQueryVariables, query: string}> {
        return requester<{data: StreamConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: StreamConnectionQueryVariables, query: string}, StreamConnectionQueryVariables>(StreamConnectionDocument, variables, options);
      },
    talk(variables: TalkQueryVariables, options?: C): Promise<{data: TalkQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TalkQueryVariables, query: string}> {
        return requester<{data: TalkQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TalkQueryVariables, query: string}, TalkQueryVariables>(TalkDocument, variables, options);
      },
    talkConnection(variables?: TalkConnectionQueryVariables, options?: C): Promise<{data: TalkConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TalkConnectionQueryVariables, query: string}> {
        return requester<{data: TalkConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TalkConnectionQueryVariables, query: string}, TalkConnectionQueryVariables>(TalkConnectionDocument, variables, options);
      },
    photos(variables: PhotosQueryVariables, options?: C): Promise<{data: PhotosQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PhotosQueryVariables, query: string}> {
        return requester<{data: PhotosQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PhotosQueryVariables, query: string}, PhotosQueryVariables>(PhotosDocument, variables, options);
      },
    photosConnection(variables?: PhotosConnectionQueryVariables, options?: C): Promise<{data: PhotosConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PhotosConnectionQueryVariables, query: string}> {
        return requester<{data: PhotosConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PhotosConnectionQueryVariables, query: string}, PhotosConnectionQueryVariables>(PhotosConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  